# Generated by Django 6.1 on 2026-08-16 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(db_index=True, max_length=32)),
                ('purpose', models.CharField(choices=[('TUITION', 'Tuition'), ('EXAM_FEE', 'Examination Fee'), ('GRADUATION', 'Graduation'), ('REGISTRATION', 'Registration Fee'), ('LIBRARY_FINE', 'Library Fine'), ('OTHER', 'Other')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('ZMW', 'ZMW (K)'), ('USD', 'USD ($)')], default='ZMW', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('DECLINED', 'Declined'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'Disputed')], db_index=True, default='PENDING', max_length=16)),
                ('cybs_transaction_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('cybs_reconciliation_id', models.CharField(blank=True, max_length=64)),
                ('cybs_response_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student_id', '-created_at'], name='payments_pa_student_bac7de_idx')],
            },
        ),
    ]
