# Generated by Django 6.1 on 2026-08-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.CharField(db_index=True, default='', max_length=32),
            preserve_default=False,
        ),
    ]
