"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY") or (
    "django-insecure-^msi5hdf^bwthf=9=-7kfpsv2u$ooe8@+saoybn_(7!r6q+1k&"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "").split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS]

# When running behind nginx (or any reverse proxy) terminating TLS, Django
# only sees a plain HTTP connection from gunicorn. Without this, request.scheme
# reports "http" even on a real https:// request — which breaks CyberSource's
# capture-context call, since it rejects http:// target origins outright.
# Safe only because gunicorn is bound to 127.0.0.1, so nothing but the proxy
# can set this header.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'payments',
]

if DEBUG:
    # CyberSource's capture-context API rejects any http:// target origin,
    # so local testing needs TLS. runserver_plus (with an ad-hoc self-signed
    # cert) is the easiest way to serve https:// on localhost.
    INSTALLED_APPS += ['django_extensions']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] 
STATIC_ROOT = BASE_DIR / 'staticfiles'  

TIME_ZONE = 'Africa/Lusaka' 

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
        "cybersource_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "cybersource.log",
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "payments": {
            "handlers": ["console", "cybersource_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

CYBERSOURCE = {
    # Legacy/default environment. Each account can override this independently.
    "ENVIRONMENT": os.getenv("CYBS_ENVIRONMENT", "test"),
 
    # One entry per acquiring bank. Add a third here if CUZ ever onboards
    # another acquirer; nothing else in the codebase needs to change.
    "ACCOUNTS": {
        "zanaco": {
            "LABEL": "Zanaco",
            "LOGO": "images/zanaco-logo.png",
            "ENVIRONMENT": os.getenv(
                "CYBS_ZANACO_ENVIRONMENT", os.getenv("CYBS_ENVIRONMENT", "test")
            ),
            "MERCHANT_ID": os.getenv("CYBS_ZANACO_MERCHANT_ID", ""),
            "KEY_ID": os.getenv("CYBS_ZANACO_KEY_ID", ""),
            "SHARED_SECRET": os.getenv("CYBS_ZANACO_SHARED_SECRET", ""),
            # Zanaco's current production approval is Visa-only.
            "ALLOWED_CARD_NETWORKS": ["VISA"],
            # Currency is NOT tied to a bank -- either bank can settle either
            # currency. This just lists what each one supports.
            "CURRENCIES": ["ZMW", "USD"],
        },
        "absa": {
            "LABEL": "Absa",
            "LOGO": "images/absa-logo.svg",
            "ENVIRONMENT": os.getenv(
                "CYBS_ABSA_ENVIRONMENT", os.getenv("CYBS_ENVIRONMENT", "test")
            ),
            "MERCHANT_ID": os.getenv("CYBS_ABSA_MERCHANT_ID", ""),
            "KEY_ID": os.getenv("CYBS_ABSA_KEY_ID", ""),
            "SHARED_SECRET": os.getenv("CYBS_ABSA_SHARED_SECRET", ""),
            "ALLOWED_CARD_NETWORKS": ["VISA", "MASTERCARD", "AMEX"],
            "CURRENCIES": ["ZMW"],
        },
    },
}
